### ISSUE TITLE
How to rotate shapeMarker using 'leaflet.rotatedMarker.js' ?

### ISSUE THREAD

**Issue by Jaumen90** [rowanwins/Leaflet.SvgShapeMarkers#13]
Hi, I'm searching for solution to rotate markers (triangle shape) using angle value from geojson file. I have no idea if it's possible to make sth like this.

Belowe is a small piece of code from geojson file:
`{ "type": "Feature", "properties": { "id": "1", "opis": "Ściana - Zachód", "url": null, "dir": 45 }, "geometry": { "type": "Point", "coordinates": [ 178.510161145464622, -0.004346263452155 ] } },`

and the final code for show result on the map:
`pointToLayer: function (feature, latlng) {
                var context = {
                    feature: feature,
                    variables: {},
                };
                return L.shapeMarker(latlng, style_points_2_0(feature));
            },
        });`

How to use "dir" value from geojson to rotate markers on the map? Is "rotationAngle" formula works for such example?

**Comment by stodge** [comment]
I think the rotation is fixed, hard coded in the s/w. I expect it would need a s/w change to support this? I think being able to set the rotation for each marker is a good feature to have though.

**Comment by gemmavnash** [comment]
I've been trying (and failing) to rotate the svgs. I thought I had it, but they're not sitting in the middle of the point. @rowanwins is there any chance you could help with this please?

**Comment by rowanwins** [comment]
Have just released v1.4.0 which includes a new `rotation` option.
