### ISSUE TITLE
"Cannot read property 'include' of undefined"

### ISSUE THREAD

**Issue by julemai** [rowanwins/Leaflet.SvgShapeMarkers#14]
Hi @rowanwins,

I have a similar problem of what was mentioned in a previous issue. I am doing what is described in the readme but when I try to use it, I get the following errors:
```
Uncaught TypeError: L.shapeMarker is not a function
```
and 
```
Uncaught TypeError: Cannot read property 'include' of undefined
    at leaflet-svg-shape-markers.js:1
```

Any suggestion would be highly appreciated!

Thanks,
Julie

**Comment by rowanwins** [comment]
I've overhauled the build and doco so hopefully this is now resolved albiet belatedly sorry @julemai
