### ISSUE TITLE
Is it possible to extend Marker instead of Path

### ISSUE THREAD

**Issue by curtis18** [rowanwins/Leaflet.SvgShapeMarkers#4]
Thank you for the plugin and I would like to ask whether it is possible to extend Marker instead of Path as I hope it can be compatible with the other plugin https://github.com/stefanocudini/leaflet-search. Since the shapeMaker is not extend from a marker, Uncaught TypeError: layer.getBounds is not a function when using leaflet-search. Thank you.

**Comment by rowanwins** [comment]
Hi @curtis18

Unfortunantly L.marker doesn't extend L.path . L.path is what provides all the color options and sizing etc. I'm not sure if there are other options if you dig into the search plugin further...

**Comment by curtis18** [comment]
hi @rowanwins 
Thanks for your reply. Since I did not receive any reply from search plugin, I forked your source and have updated the marker to extend from L.Marker. Please feel free to discuss if you want the shape marker to extend to L.Marker.

**Comment by rowanwins** [comment]
Hmm interesting, that you can get the same visual results converting it to a L.marker! If you'd like to put it into a pull request then go ahead, would be interesting to see!

**Comment by curtis18** [comment]
A pull request has been submitted, please feel free to change. Thank you!

**Comment by gemmavnash** [comment]
@rowanwins is there any progress on merging this change to extend marker instead of path? I'd really like to be able to use shapemarkers with @zakjan's lasso, but can't currently and I'm not confident enough to merge this locally myself.

**Comment by gemmavnash** [comment]
@curtis18 did you merge this locally? I really want to use your fork, but the setStyle functionality isn't available, so it's not complete.

**Comment by jonoyuan** [comment]
L.CircleMarker offers some more functionality, though I'm not sure if it's compatible with leaflet-search or leaflet-lasso. It would be as simple as replacing [`L.Path.extend()` here with `L.CircleMarker.extend()`](https://github.com/rowanwins/Leaflet.SvgShapeMarkers/blob/4ead872a454e8380a63ead53477bf0c07cbda6dc/dist/leaflet-svg-shape-markers.js#L45)

I *think* this means it will inherit most of the methods you defined explicitly, including `setLatLng`, `setRadius`, etc.

**Comment by rowanwins** [comment]
This is now done in v.1.4.0 - thanks all for the suggestions and contributions.
