### ISSUE TITLE
TypeError: this._renderer._updateShape is not a function

### ISSUE THREAD

**Issue by ikhudo** [rowanwins/Leaflet.SvgShapeMarkers#6]
Getting this error when using with leaflet 1.5.1

**Comment by rowanwins** [comment]
Sorry for the very slow reply. 

I'm not seeing this error with `1.5.1`, if you're still having issues can you show me how you're using the plugin?

**Comment by mattbarton44** [comment]
I've just encountered this problem and it stumped me for a couple of hours.

Looks like it only occurs when you set the preferCanvas option in Leaflet to true.

**Comment by rowanwins** [comment]
Yeah ok I've confirmed that behaviour. 

So it seems that there is no `_updateShape` method available on a leaflet renderer when `preferCanvas` method is true, not sure what the workaround is yet but I'll have a think.

**Comment by BaharWeb** [comment]
I have the same issue when trying to use this._renderer._updatemyMarker for my custom marker. Any idea how to solve this?

**Comment by HairyFotr** [comment]
Adding {renderer: L.svg()} to the marker's options removes the error, and the markers show up, but they are below other map layers, and mouse interaction does not seem to work.

**Comment by dvandeijl** [comment]
This is still an issue. Since L.circleMarker(latlng) does work with canvas rendering
