### ISSUE TITLE
TypeError: leaflet__WEBPACK_IMPORTED_MODULE_4___default.a.shapeMarker is not a function

### ISSUE THREAD

**Issue by npcode15** [rowanwins/Leaflet.SvgShapeMarkers#7]
Hello, I am getting the following error when I am trying to use this library without using the following line:
<script src="leaflet-svg-shape-markers/dist/leaflet-svg-shape-markers.min.js"></script>
(I already installed the library via npm)

**TypeError: leaflet__WEBPACK_IMPORTED_MODULE_4___default.a.shapeMarker is not a function
    at VueComponent.eval (Map.vue?108f:169)
    at Array.forEach (<anonymous>)
    at VueComponent.eval (Map.vue?108f:159)
    at Array.forEach (<anonymous>)
    at eval (Map.vue?108f:155)**

If I do use the suggested way:
<script src="leaflet-svg-shape-markers/dist/leaflet-svg-shape-markers.min.js"></script>

I get the following error:
**Uncaught ReferenceError: L is not defined**

I am already importing leaflet in the vue-component as
**import L from "leaflet";**

Can you please suggest, how can I correctly use this library without disrupting the existing Leaflet imports.

Thank you.

**Comment by rowanwins** [comment]
Hi @npcode15 

Sorry for the slow reply.
I've just released v1.2.0 to npm which has better methods for pulling in the library. In a vuejs project you should be able to do something like rather than add it via the script.

````
import L from "leaflet";
import 'leaflet-svg-shape-markers'
````

 Cheers
